import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import * as git from '../server/git.mjs';import {scanProject} from '../server/project.mjs';
const exec=promisify(execFile);
test('diff review distinguishes staged, unstaged, deleted, and untracked content without exposing hidden files',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'atlas-git-'));const run=args=>exec('git',args,{cwd:root});try{
 await run(['init','-q']);await writeFile(path.join(root,'file.ts'),'export const n = 1;\n');await writeFile(path.join(root,'gone.ts'),'export const gone = true;\n');await run(['add','.']);await run(['-c','user.name=Test','-c','user.email=test@example.com','-c','core.hooksPath=/dev/null','commit','-qm','fixture']);
 await writeFile(path.join(root,'file.ts'),'export const n = 2;\n');await run(['add','file.ts']);await writeFile(path.join(root,'file.ts'),'export const n = 3;\n');await rm(path.join(root,'gone.ts'));await writeFile(path.join(root,'.env'),'private');await writeFile(path.join(root,'new.ts'),'export const fresh = true;\n');const p=await scanProject(root);
 const changes=await git.listChanges(p,'working');assert(changes.files.some(f=>f.path==='gone.ts'),JSON.stringify(changes));assert(changes.files.some(f=>f.path==='new.ts'));assert(!changes.files.some(f=>f.path==='.env'));
 assert.match((await git.fileDiff(p,'file.ts','staged')).text,/\+export const n = 2/);assert.match((await git.fileDiff(p,'file.ts','unstaged')).text,/-export const n = 2/);assert.match((await git.fileDiff(p,'gone.ts','working')).text,/-export const gone/);await assert.rejects(git.fileDiff(p,'../outside.ts','working'));
}finally{await rm(root,{recursive:true,force:true});}});
test('read-only Git review never executes a repository clean filter',async()=>{const {access}=await import('node:fs/promises');const root=await mkdtemp(path.join(os.tmpdir(),'atlas-filter-'));const run=args=>exec('git',args,{cwd:root});try{await run(['init','-q']);await writeFile(path.join(root,'file.ts'),'const n=1;\n');await writeFile(path.join(root,'.gitattributes'),'*.ts filter=atlas\n');await run(['add','.']);await run(['-c','user.name=Test','-c','user.email=test@example.com','-c','core.hooksPath=/dev/null','commit','-qm','fixture']);await writeFile(path.join(root,'filter.mjs'),"import fs from 'node:fs';fs.writeFileSync('FILTER_RAN','yes');process.stdin.pipe(process.stdout);");await run(['config','filter.atlas.clean','node ./filter.mjs']);await writeFile(path.join(root,'file.ts'),'const n=2;\n');const p=await scanProject(root);await git.listChanges(p,'working');await git.fileDiff(p,'file.ts','working');await assert.rejects(access(path.join(root,'FILTER_RAN')));}finally{await rm(root,{recursive:true,force:true});}});
