import {evidenceLevel} from './evidence.js';
import {markdown} from './markdown.js';
export const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHtml;
const list=items=>items?.length?`<ul>${items.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`:'';
export const evidenceButtons=refs=>(refs||[]).map(r=>`<button class="text-button" data-evidence-path="${e(r.path)}" data-evidence-line="${r.line}">${e(r.path)}:${r.line} · Preview</button>`).join('');
export function coachingMarkup(coaching,messageIndex,{message={},files=[],records=[]}={}){
 if(!coaching)return '';
 const claims=coaching.claims||[],findings=coaching.findings||[],lesson=coaching.lesson;
 const trust=(kind,item,index)=>{
  const {level,record}=evidenceLevel(records,kind,item,message,files);
  const labels={'suggestion':'AI suggestion','source-supported':'Source-supported · user checked','independently-verified':'Independently verified · user reported'};
  return `<div class="evidence-trust"><strong class="trust-badge trust-${level}">${labels[level]}</strong>${record?`<details><summary>Recorded check · ${e(record.outcome)}</summary><p><strong>Steps:</strong> ${e(record.steps)}</p><p><strong>Expected:</strong> ${e(record.expected)}</p><p><strong>Observed:</strong> ${e(record.observed)}</p>${record.artifact?`<p><strong>Check reference:</strong> ${e(record.artifact)}</p>`:''}<small>${e(record.date)} · user reported; Code Atlas did not execute this check</small></details>`:''}<button class="text-button" data-record-evidence="${index}" data-evidence-kind="${kind}" data-evidence-message="${messageIndex}" ${item.evidence?.length?'':'disabled'}>Record my check</button></div>`;
 };
 return `${claims.length?`<details class="evidence-panel"><summary>Evidence & assumptions · ${claims.length} claims</summary><p>Checked locations are real supplied source, not proof that the AI interpretation is correct.</p>${claims.map((c,i)=>`<section class="evidence-card">${trust('claim',c,i)}<div class="markdown claim-text">${markdown(c.claim)}</div><small>${c.evidence?.length?'Source location checked':'Missing source evidence'}${c.invalidEvidence?` · ${c.invalidEvidence} unsupported references removed`:''}</small>${evidenceButtons(c.evidence)}${c.assumptions?.length?'<h4>Assumptions</h4>'+list(c.assumptions):''}${c.unknowns?.length?'<h4>Still unknown</h4>'+list(c.unknowns):''}</section>`).join('')}</details>`:''}
 ${findings.map((f,i)=>`<section class="finding-card">${trust('finding',f,i)}<div class="finding-label">${e(f.severity)} severity · ${e(f.confidence)} AI confidence</div><h3>${e(f.title)}</h3><p><strong>Trigger:</strong> ${e(f.trigger)}</p><p><strong>Consequence:</strong> ${e(f.consequence)}</p>${evidenceButtons(f.evidence)}${!f.evidence?.length?'<p class="notice">No supporting source location. Treat this as an unsupported hypothesis.</p>':''}<h4>How to check</h4>${list(f.verification)}${f.missingTests?.length?'<h4>Suggested missing tests</h4>'+list(f.missingTests):''}<button class="secondary" data-verify-message="${messageIndex}" data-verify-finding="${i}">Verify this finding</button></section>`).join('')}
 ${(coaching.recommendations||[]).map((r,i)=>`<section class="recommendation-card">${trust('recommendation',r,i)}<div class="finding-label">${e(r.category)} · ${e(r.priority)} priority · ${e(r.confidence)} AI confidence</div><h3>${e(r.title)}</h3><p>${e(r.reason)}</p><h4>Suggested change</h4><p>${e(r.change)}</p><h4>Why it helps</h4><p>${e(r.benefit)}</p><h4>Trade-off / when to leave it alone</h4><p>${e(r.tradeoff)}</p>${evidenceButtons(r.evidence)}${r.caution?`<p class="notice">${e(r.caution)}</p>`:''}<small>Source locations checked, not proof that this change is needed.</small><h4>Checks before changing</h4>${list(r.verification)||'<p>Ask for a verification plan before changing behavior.</p>'}<button class="secondary" data-plan-message="${messageIndex}" data-plan-recommendation="${i}">Plan this change</button></section>`).join('')}
 ${lesson?`<section class="lesson-card"><small>Teach-back · ${e(lesson.concept||'Code reasoning')}</small>${lesson.question?`<div class="markdown">${markdown(lesson.question)}</div>`:''}${lesson.feedback?`<div class="markdown">${markdown(lesson.feedback)}</div>`:''}${lesson.misconceptions?.length?'<h4>Revisit these ideas</h4>'+list(lesson.misconceptions):''}${lesson.nextExercise?`<div class="markdown"><strong>Next exercise:</strong>${markdown(lesson.nextExercise)}</div>`:''}<small>AI assessment: ${e(lesson.assessment)} · tentative, not a mastery score</small></section>`:''}`;
}
